# Generated by Django 5.0.6 on 2024-07-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electeur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='electeur',
            name='mot_de_passe',
            field=models.CharField(default='123', max_length=8),
        ),
    ]
