# Generated by Django 5.0.6 on 2024-07-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_electeur_actif_electeur_mot_de_passe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electeur',
            name='mot_de_passe',
            field=models.CharField(default='123', max_length=128),
        ),
    ]
